trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    appName: 'book-processing'
    deployToSlotOrASE: false
    package: $(System.DefaultWorkingDirectory)
    startUpCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'